config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root "lead#merchant"
  root "lead#home"
  get "lead/merchant" => "lead#merchant", path: "restaurants"
  get "lead/foodies" => "lead#foodies", path: "diners"
  get "lead/pricing" => "lead#pricing", path: "pricing"
  post "lead/create" => "lead#create"
  get "lead/thank_you" => "lead#thank_you", path: "thanks"
  get "lead/query_community" => "lead#query_community", :as => 'query_community'
  get "lead/query_unit" => "lead#query_unit", :as => 'query_unit'
  post "lead/seek_status" => "lead#seek_status", :as => 'seek_status'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lead.rb
class Lead < ApplicationRecord
  validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  # validates :email, uniqueness: true
  validates_uniqueness_of :email, :scope => :lead_type
end

app/controllers/application_controller.rb
require 'rest_client'

class ApplicationController < ActionController::Base
  # protect_from_forgery with: :null_session

  protected

  def join_invite_button(category, action, label, client_id = '555')
    params = {
      v: 1,
      tid: "UA-91685349-1",
      cid: client_id,
      t: "event",
      ec: category,
      ea: action,
      el: label
    }
    begin
      RestClient.get("https://www.google-analytics.com/collect", params: params, timeout: 4, open_timeout: 4)
      return true
    rescue  RestClient::Exception => rex
      return false
    end
  end

end

app/controllers/lead_controller.rb
class LeadController < ApplicationController

  def index
    @lead = Lead.new
  end
  
  def home
  end
  
  def merchant
    if request.referer != nil && URI(request.referer).path == "/"
      gon.event_tracker = {category: "ButtonClick", action: "Merchants", label: "To view merchants page"}
    end
    @lead = Lead.new
  end

  def foodies
    if request.referer != nil && URI(request.referer).path == "/"
      gon.event_tracker = {category: "ButtonClick", action: "Diners", label: "To view diners page"}
    end
    @lead = Lead.new
  end

  def thank_you
    if params[:pricing][:pricing_type] == "free"
      gon.event_tracker = {category: "Pay", action: "Free", label: ""}
    elsif params[:pricing][:pricing_type] == "usd15"
      gon.event_tracker = {category: "Pay", action: "Usd15", label: ""}
    else
      gon.event_tracker = {category: "Pay", action: "Usd25", label: ""}
    end
  end

  def create
    @lead = Lead.new(lead_params)
    if @lead.lead_type == "foodie"
      join_invite_button("Join Invite List", "ClickedButton", "")
      if @lead.save
        LeadMailer.welcome_email(@lead).deliver_later
        redirect_to 'https://docs.google.com/forms/d/e/1FAIpQLScpTOsUuHJeMQZg27Uya7dqo_9F18mgARhU3f-IwroAYykqpg/viewform?c=0&w=1'
        # respond_to do |format|
        #   format.js 
        # end
      else
        @error = @lead.errors.full_messages.first
        if @error == "Email is invalid" 
          respond_to do |format|
            @error
            format.js 
          end
        else
          redirect_to 'https://docs.google.com/forms/d/e/1FAIpQLScpTOsUuHJeMQZg27Uya7dqo_9F18mgARhU3f-IwroAYykqpg/viewform?c=0&w=1'
        end
      end
    else
      # gon.event_tracker = {category: "Get Started", action: "ClickedButton", label: ""}
      join_invite_button("Get Started", "ClickedButton", "")
      if @lead.save
        LeadMailer.welcome_email(@lead).deliver_later
        redirect_to lead_pricing_path
      else
        @error = @lead.errors.full_messages.first
        if @error == "Email is invalid" 
          respond_to do |format|
            @error
            format.js 
          end
        else
          redirect_to lead_pricing_path
        end
      end
    end
  end

  def pricing
  end

  def query_community
    @communities = ["Bandar Puteri", "Bandar Putra", "Bandar Klang", "Bandar Bomb", "Tropicana Golf and Country Club", "USJ 11/4", "KGSAAS - Greenville"]
    render json: @communities
  end

  def query_unit
    @units = ["23, USJ11/4B", "12, USJ11/4C", "22, USJ11/4B"]
    render json: @units
  end

  def seek_status
    @user = Lead.find_by(email: params[:email])
    if @user != nil 
      render json: @user
    else
      render json: {message: "User is not found"}
    end
  end

  private
  
  def lead_params
    params.require(:lead).permit(:email, :lead_type)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lead_helper.rb
module LeadHelper
end

app/views/layouts/_footer.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-91685349-1', 'potacto.com');
  ga('send', 'pageview');

  if (typeof gon.event_tracker !== "undefined") {
    ga('send', 'event', gon.event_tracker.category, gon.event_tracker.action, gon.event_tracker.label);
  }

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= include_gon %>
    <%= csrf_meta_tags %>

    <script src="https://use.fontawesome.com/2263772b85.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track'=> true %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track'=> true %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=3.0">
    <% if request.fullpath == "/restaurants" %>
      <meta property="og:url"                content="http://www.potacto.com/restaurants" />
      <meta property="og:title"              content="Offer an Unparalleled Dining Experience" />
      <meta property="og:description"        content="Market Your Restaurant, Chat With Customers, Manage Waitlist & Bookings - All in One App" />
      <meta property="og:image"              content="http://www.potacto.com/assets/consumer_chat.png" />
    <% else %>
      <meta property="og:url"                content="http://www.potacto.com/diners" />
      <meta property="og:title"              content="Dining Out Has Never Been Easier" />
      <meta property="og:description"        content="Discover Restaurants, Queue Remotely, Book and Enquire Easily - All in One App" />
      <meta property="og:image"              content="http://www.potacto.com/assets/foodies_image_2-7e3ac1e9d37835589f1afc02348bd171769e49277bc10b3cce758ed9087e5407.png" />
    <% end %>
  </head>

  <body>
    <%= favicon_link_tag 'favicon.ico' %>
    <% if request.fullpath != "/" %>
    <div class="navbar transparent navbar-default navbar-fixed-top" id="foodie_nav">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle Navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>

            <%= link_to image_tag("potactologo.png", alt: "logo", class: "navbar_logo"), '/', class: "navbar_link navbar-brand" %> 
          </div> <!-- end div class="navbar-header" -->
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
              <li>
                <%= link_to "Diners", lead_foodies_path, class: "foodie_nav_link_1 navbar_link" %>
              </li> 
              <li>
                <%= link_to "Restaurant Owners", lead_merchant_path, class: "foodie_nav_link_1 navbar_link" %>
              </li>
              <% if @lead != nil %>
              <li>
                <%= link_to "Features", "#", class: "foodie_nav_link_1 navbar_link", id: "features" %>
              </li> 
              <% end %>
              <% if request.fullpath == "/diners" %>
              <li>
                <%= link_to "Join Our Invite List", "#", class: "foodie_nav_link_1 navbar_link", id: "sign_up_for_beta" %>
              </li> 
              <% elsif request.fullpath == "/restaurants" %>
              <li>
                <%= link_to "Get Started", "#", class: "foodie_nav_link_1 navbar_link", id: "sign_up_for_beta" %>
              </li> 
              <% end %>

            </ul>
          </div> <!-- end div class="collapse navbar-collapse" -->
        </div> <!-- end div class="container" -->
    </div> <!-- end div class="navbar navbar-default navbar-fixed-top" -->
    <% end %>

    <%= Gon::Base.render_data({}) %>
    <%= yield %>

    <% if Rails.env == "production" %>
      <%= render "layouts/footer" %>
    <% end %>

  </body>

</html>

app/views/lead/create.js.erb
// $("#form_button").html('Received').css('color', 'white').css('background', 'rgba(154,59,59,1)').fadeIn();
// $("#form_button").attr('disabled',true);
<% if @error == "Email is invalid" %>
  $(".canvas").hide();
  $(".modal_text").text("Please key in a valid email").show();
<% else %>
  $(".canvas").attr("height","200").show();
var start = 120;
var mid = 138;
var end = 180;
var width = 9;
var leftX = start;
var leftY = start + 30;
var rightX = mid + 0.5;
var rightY = mid + 30 - 1.5;
var animationSpeed = 20;
var ctx = $('.canvas')[0].getContext('2d');
ctx.lineWidth = width;
ctx.strokeStyle = 'rgba(0, 150, 0, 1)';
for (i = start; i < mid; i++) {
    var drawLeft = window.setTimeout(function () {
        ctx.beginPath();
        ctx.moveTo(start, start + 30);
        ctx.lineTo(leftX, leftY);
        ctx.lineCap = 'round';
        ctx.stroke();
        leftX++;
        leftY++;
    }, 1 + (i * animationSpeed) / 3);
}
for (i = mid; i < end; i++) {
    var drawRight = window.setTimeout(function () {
        ctx.beginPath();
        ctx.moveTo(leftX + 2, leftY - 3);
        ctx.lineTo(rightX, rightY);
        ctx.stroke();
        rightX++;
        rightY--;
    }, 1 + (i * animationSpeed) / 3);
}

  $(".modal_text").text("You are now in our invite list! Fill in this survey form to receive exclusive deals when we launch!").show();
  $(".google_form").show();
<% end %>

app/views/lead/foodies.html.erb
<title>Diners - Potacto</title>
<%= image_tag("foodies_image_2.png", style: "display:none;") %>
<div class="foodies_1">
  <p class="foodies_tagline">From discovering what to eat to getting seated at the dining table, manage all of it at your fingertips in one app</p>
  <div class="merchant_3_form">
    <%= form_for @lead, url: lead_create_path(format: 'js'), remote: true, :method => 'post' do |form| %>

      <%= form.text_field :email, placeholder: "Enter your email...", type: 'text', class: 'merchant_3_form_input' %>
      <%= form.hidden_field :lead_type,  :value => "foodie" %>
      <span><%= form.button "Join the Potacto Invite List", class: "btn btn-primary merchant_3_form_btn", data: {target: "#myModal", toggle: "modal"}%></span>

    <% end %>
  </div>
</div>

<div class="container how_it_works">
  <br>
  <p class="how_it_works_title">HOW IT WORKS</p>
  <div class="col-md-4 col-xs-12 how_it_works_des">
    <%= image_tag("one.png", class: "how_it_works_pic") %>
    <p>Browse for what you want to eat based on price, reviews, food type, location and waiting times. <strong>Receive smart suggestions</strong> based on the mood of your appetite!</p>
  </div>
  <div class="col-md-4 col-xs-12 how_it_works_des">
    <%= image_tag("two.png", class: "how_it_works_pic") %> 
    <p>Place a <strong>table booking</strong> if needed. Still not sure about the food or service? <strong>Chat directly with the restaurant manager</strong> on any enquiries.</p>
  </div>
  <div class="col-md-4 col-xs-12 how_it_works_des">
    <%= image_tag("three.png", class: "how_it_works_pic") %> 
    <p>Arrive at the restaurant and dine with a peace of mind. If your restaurant of choice does not offer bookings and that there is a long queue, <strong>queue virtually</strong> by scanning a QR code and <strong>be notified through your phone when your table is ready</strong>.</p>
  </div>
</div>
<hr>

<div class="container features">
  <div class="how_it_works_title_div"><p class="how_it_works_title">FEATURES</p></div>
  <br>
  <div class="row merchant_2_description">
    <div class="col-md-4 col-xs-12 foodie_2_pic_1"></div>
    <div class="col-md-8 col-xs-12 merchant_2_text">
      <i class="fa fa-3x fa-search" aria-hidden="true"></i><span class="merchant_2_text_header">Restaurant Discovery</span>
      <hr>
      <p>Use our food assistant to recommend interesting restaurants! Otherwise, conveniently search for good restaurants anywhere for food of your preference using various filters such as location, food type, reviews, price and waiting times</p>
    </div>
  </div>

  <div class="row merchant_2_description" style="min-height: 280px;">
    <div class="visible-xs-12 hidden-md hidden-lg col-xs-12 foodie_2_pic_2"></div>
    <div class="col-md-8 col-xs-12 merchant_2_text">
      <span><i class="fa fa-3x fa-hourglass-half" aria-hidden="true"></i></span><span class="merchant_2_text_header">Queue Remotely</span>
      <hr>
      <p>Get into queues with a quick QR code scan at the restaurant reception and wander around with a peace of mind while waiting for your table to be ready, as the restauranteur will send you push notifications minutes before your turn is up. No more frustrations with queuing</p>
    </div>
    <div class="hidden-xs hidden-sm col-md-4 foodie_2_pic_2"></div>
  </div>

  <div class="row merchant_2_description">
    <div class="col-md-4 col-xs-12 foodie_2_pic_3"></div>
    <div class="col-md-8 col-xs-12 merchant_2_text">
      <i class="fa fa-3x fa-address-book" aria-hidden="true"></i><span class="merchant_2_text_header">Table Booking</span>
      <hr>
      <p>Place a table booking immediately after viewing reviews and menu and being satisfied with what the restaurant has got to offer</p>
    </div>
  </div>

  <div class="row merchant_2_description">
    <div class="visible-xs-12 hidden-md hidden-lg col-xs-12 foodie_2_pic_4"></div>
    <div class="col-md-8 col-xs-12 merchant_2_text">
      <i class="fa fa-4x fa-mobile" aria-hidden="true"></i><span class="merchant_2_text_header">Chat Enquiries</span>
      <hr>
      <p>Message restaurant managers with our in-built chat function for enquiries, enabling a convenient, direct and continuous conversation as you wish</p>
    </div>
    <div class="hidden-xs hidden-sm col-md-4 foodie_2_pic_4"></div>
  </div>

  <br>
</div>

<div class="merchant_3">
  <p class="merchant_3_header">Drop your email with us to be first in the know and receive exclusive deals when our service is ready</p>
  <br>
  <div class="merchant_3_form">

  <%= form_for @lead, url: lead_create_path(format: 'js'), remote: true, :method => 'post' do |form| %>

    <%= form.text_field :email, placeholder: "Enter your email...", type: 'text', class: 'merchant_3_form_input' %>
    <%= form.hidden_field :lead_type,  :value => "foodie" %>
    <span><%= form.button "Join the Potacto Invite List", class: "btn btn-primary merchant_3_form_btn", data: {target: "#myModal", toggle: "modal"}%></span>

  <% end %>

  </div>

  <div class="copyright">
    <h5>&copy; 2017 Potacto. All Rights Reserved.</h5>
  </div>
</div>

<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Join the Potacto Invite List</h4>
      </div>
      <div class="modal-body">
        <canvas height="0" class="canvas"></canvas>
        <p class="modal_text">Redirecting...</p>
      </div>
 
    </div>

  </div>
</div>

app/views/lead/form_submit.js.erb
// $(".modal_form").fadeOut();
// $(".canvas").attr("height","200");
// $(".modal_text").text("You are now in our invite list! Fill in this survey form to receive exclusive deals when we launch!");

// var start = 120;
// var mid = 138;
// var end = 180;
// var width = 9;
// var leftX = start;
// var leftY = start + 30;
// var rightX = mid + 0.5;
// var rightY = mid + 30 - 1.5;
// var animationSpeed = 20;
// var ctx = $('.canvas')[0].getContext('2d');
// ctx.lineWidth = width;
// ctx.strokeStyle = 'rgba(0, 150, 0, 1)';
// for (i = start; i < mid; i++) {
//     var drawLeft = window.setTimeout(function () {
//         ctx.beginPath();
//         ctx.moveTo(start, start + 30);
//         ctx.lineTo(leftX, leftY);
//         ctx.lineCap = 'round';
//         ctx.stroke();
//         leftX++;
//         leftY++;
//     }, 1 + (i * animationSpeed) / 3);
// }
// for (i = mid; i < end; i++) {
//     var drawRight = window.setTimeout(function () {
//         ctx.beginPath();
//         ctx.moveTo(leftX + 2, leftY - 3);
//         ctx.lineTo(rightX, rightY);
//         ctx.stroke();
//         rightX++;
//         rightY--;
//     }, 1 + (i * animationSpeed) / 3);
// }

app/views/lead/home.html.erb
<title>Home - Potacto</title>

<div class="home_1">
  <%= link_to image_tag("potactologo.png", class: "home_logo"), '/'%> 

  <p class="home_1_tagline">Dining out has never been easier</p>
  <br>
  <p class="home_1_subtagline">An all-in-one app for diners and restaurateurs to interact</p>
  <br>
  <p class="home_1_subsubtagline">Discover smartly | Book conveniently</p>
  <p class="home_1_subsubtagline" style="margin-top: -10px;">Queue efficiently | Enquire freely</p>
  <br>

    <div class="home_button_div">
      <%= form_for :go_foodies, enforce_utf8: false, url: lead_foodies_path, :method => 'get' do |f| %>

      <%= submit_tag "Diners", name: nil, class: "btn btn-default home_button_1" %>
      <% end %>
    </div>

    <div class="home_button_div">
      <%= form_for :go_restaurants, enforce_utf8: false, url: lead_merchant_path, :method => 'get' do |f| %>
      <%= submit_tag "Restaurants", name: nil, class: "btn btn-default home_button_2" %>
      <% end %>
    </div>
    
  <div class="copyright">
    <h5>&copy; 2017 Potacto. All Rights Reserved.</h5>
  </div>
</div>

app/views/lead/index.html.erb
<div style="height:10px;"></div>

<div class="row heading_top">
  <div class="col-md-6 heading_1">
    <div><h1 class="header_title">FOODIES</h1></div>
    <h2 class="header_text">Dining simplified</h2>
  </div>
  <div class="col-md-6 heading_2">
    <h1 class="header_title">RESTAURATUERS</h1>
    <h2 class="header_text">Full-suite customer <br/> management solution</h2>
  </div>

</div>

<div style="height:10px;"></div>

<div class="row what_and_how_section">
  

</div>

<div style="height:10px;"></div>

<div class="row foodie_section">
  <div class="container">
    <h1>One food app to discover, quality-check, join queue lines, book and enquire restaurants</h1>
  </div>
  <br>
  <div class="row">
    <div class="col-md-3 icon_section"><i class="fa fa-3x fa-search" aria-hidden="true"></i></div>
    <div class="col-md-7 text_section"><span>Conveniently search for restaurants of your preference using various filters such as location, food type and waiting times</span></div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-3 icon_section"><i class="fa fa-3x fa-hourglass-half" aria-hidden="true"></i></div>
    <div class="col-md-7 text_section"><span>Wander around with a peace of mind while waiting for your table to be ready, as the restauranteur will send you push notifications minutes before your turn is up</span></div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-3 icon_section"><i class="fa fa-3x fa-address-book" aria-hidden="true"></i></div>
    <div class="col-md-7 text_section"><span>Place a table booking immediately after viewing reviews and menu and being satisfied with what the restaurant has got to offer</span></div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-3 icon_section"><i class="fa fa-5x fa-mobile" aria-hidden="true"></i></div>
    <div class="col-md-7 text_section"><span>Message restaurant managers with our in-built chat function for enquiries, enabling a convenient a continuous conversation as you wish</span></div>
  </div>

</div>

<div style="height:10px;"></div>

<div class="row restaurant_section">
  <div class="container">
    <h1>One dashboard to manage queues, enquiries and bookings</h1>
  </div>
  <div class="col-md-4 section">
    <i class="fa fa-5x fa-users" aria-hidden="true"></i>
    <p class="title">Waitlist Management</p>
    <p class="text">Don't lose customers just because you can't sit them quick enough. Manage your customer queues effectively by sending them notifications when their table is ready, and by enabling them to constantly monitor waiting times</p>

  </div>
  <div class="col-md-4 section">
    <i class="fa fa-5x fa-comments" aria-hidden="true"></i>
    <p class="title">Real-time Messaging</p>
    <p class="text">Offer your customers the ease of contacting you via a chat system. Stay engaged in conversations with your potential customers anytime, anywhere</p>

  </div>
  <div class="col-md-4 section">
    <i class="fa fa-5x fa-table" aria-hidden="true"></i>
    <p class="title">Booking Management</p>
    <p class="text">Offer convenience to your customers who want to make reservations at your restaurant and manage bookings seamlessly</p>

  </div>
</div>

<div style="height:10px;"></div>

<div id="contact_us">
  <div class="contact_us_1">
    
  </div>

  <div class="contact_us_2">

  <h1>Stay Connected</h1>
  <h3>Drop us your email or any comments to stay updated with our progress, and be notified once our service is ready</h3>

  <%= form_for @lead, url: lead_index_path(format: 'js'), remote: true, :method => 'post' do |form| %>
    <div class="form-group">
      <%= form.text_field :name, placeholder: "Name",type: 'text', required: true, class: 'form-control'  %>
    </div>

    <div class="form-group">
      <%= form.text_field :email, placeholder: "Email", type: 'text', required: true, class: 'form-control'  %>
    </div>

    <div class="form-group">
      <%= form.text_area :comments, placeholder: "Comments", type: 'text', required: true, class: 'form-control'  %>
    </div>
    
    <div class="form-actions">
      <%= form.button "Stay In Touch", class: "btn btn-primary", id: "form_button"  %>
    </div>
  <% end %>

  </div>
    
</div>

app/views/lead/merchant.html.erb
<title>Restaurants - Potacto</title>

<div class="merchant_1">
  <p class="merchant_tagline">Make your brand known. Allow your customers to reach you better, and provide a hassle-free dine out experience to your customers</p>
  <div class="merchant_3_form">
    <%= form_for @lead, url: lead_create_path(format: 'js'), remote: true, :method => 'post' do |form| %>

      <%= form.text_field :email, placeholder: "Enter your email...", type: 'text', class: 'merchant_3_form_input' %>
      <%= form.hidden_field :lead_type,  :value => "merchant" %>
      <span><%= form.button "Get Started", class: "btn btn-primary merchant_3_form_btn", data: {target: "#myModal", toggle: "modal"}%></span>

    <% end %>
  </div>
</div>


<div class="container features">
  <br>
  <div class="row merchant_2_description">
    <div class="col-md-4 col-xs-12 merchant_2_pic_1"></div>
    <div class="col-md-8 col-xs-12 merchant_2_text">
      <i class="fa fa-3x fa-users" aria-hidden="true"></i><span class="merchant_2_text_header">Waitlist Management</span>
      <hr>
      <p>Don't lose customers or irritate them by letting them standing in queues just because you can't sit them quick enough. Manage your customer queues effectively by sending them notifications when their table is ready, and by enabling them to constantly monitor waiting times</p>
    </div>
  </div>

  <div class="row merchant_2_description">
    <div class="visible-xs-12 hidden-md hidden-lg col-xs-12 merchant_2_pic_2"></div>
    <div class="col-md-8 col-xs-12 merchant_2_text">
      <i class="fa fa-3x fa-comments" aria-hidden="true"></i><span class="merchant_2_text_header">Real-time Messaging</span>
      <hr>
      <p>Offer your customers the ease of contacting you via a chat system. Communicate with your potential customers anytime, anywhere</p>
    </div>
    <div class="hidden-xs hidden-sm col-md-4 merchant_2_pic_2"></div>
  </div>

  <div class="row merchant_2_description">
    <div class="col-md-4 col-xs-12 merchant_2_pic_3"></div>
    <div class="col-md-8 col-xs-12 merchant_2_text">
      <i class="fa fa-3x fa-bullhorn" aria-hidden="true"></i><span class="merchant_2_text_header">Marketing Tools</span>
      <hr>
      <p>Market your brand to diners by leveraging on our strategically placed banner ads and push notification advertising system. Shape your brand image by customising your restaurant profile and showcasing your offers</p>
    </div>
  </div>

  <div class="row merchant_2_description">
    <div class="visible-xs-12 hidden-md hidden-lg col-xs-12 merchant_2_pic_4"></div>
    <div class="col-md-8 col-xs-12 merchant_2_text">
      <i class="fa fa-3x fa-line-chart" aria-hidden="true"></i><span class="merchant_2_text_header">Business Intelligence & Customer Analytics</span>
      <hr>
      <p>Understand your customers’ preference to improve services and offering based on our proprietary software. Make data-driven decisions to optimise your cost and maximise revenue generation</p>
    </div>
    <div class="hidden-xs hidden-sm col-md-4 merchant_2_pic_4"></div>
  </div>

  <div class="row merchant_2_description">
    <div class="col-md-4 col-xs-12 merchant_2_pic_5"></div>
    <div class="col-md-8 col-xs-12 merchant_2_text">
      <i class="fa fa-3x fa-table" aria-hidden="true"></i><span class="merchant_2_text_header">Booking Management</span>
      <hr>
      <p>Increase customer conversion by offering your customers convenience in making reservations at your restaurant. Accept and decline booking requests, manage their booking enquiries, and view the upcoming ones in a single dashboard</p>
    </div>
  </div>
  <br>
  <br>
  <br>
</div>

<div class="merchant_3">
  <p class="merchant_3_header">Market your brand. Attract customers with your unique restaurant profile. Make happy customers by giving them all the convenience they need</p>
  <br>
  <div class="merchant_3_form">

  <%= form_for @lead, url: lead_create_path(format: 'js'), remote: true, :method => 'post' do |form| %>

    <%= form.text_field :email, placeholder: "Enter your email...", type: 'text', class: 'merchant_3_form_input'  %>
    <%= form.hidden_field :lead_type,  :value => "merchant" %>
    <span><%= form.button "Get Started", class: "btn btn-primary merchant_3_form_btn", data: {target: "#myModal", toggle: "modal"}%></span>

  <% end %>

  </div>

  <div class="copyright">
    <h5>&copy; 2017 Potacto. All Rights Reserved.</h5>
  </div>
</div>

<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Get Started</h4>
      </div>
      <div class="modal-body">
        <canvas height="0" class="canvas"></canvas>
        <p class="modal_text">Redirecting...</p>
      </div>
 
    </div>

  </div>
</div>